Make access to fts_config.username conditional
Currently, all non-FTS tests are broken due to the following issue:

[2016-12-04 10:02:02,469: ERROR/MainProcess] Task perfrunner.helpers.worker.task_run_workload[d1118e9b-2796-4a24-9990-589164e7fe34] raised unexpected: AttributeError("'NoneType' object has no attribute 'username'",)
Traceback (most recent call last):
  File "/workspace/workspace/calypso/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/workspace/workspace/calypso/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/workspace/workspace/calypso/perfrunner/helpers/worker.py", line 26, in task_run_workload
    wg = WorkloadGen(settings, target, timer=timer)
  File "/workspace/workspace/calypso/spring/wgen.py", line 697, in __init__
    self.rest_auth = (self.ws.fts_config.username, self.ts.password)
AttributeError: 'NoneType' object has no attribute 'username'

As a temporary workaround we could create rest_auth only for
fts workers.

Change-Id: I3eeaefd96e7f9885c450db35a944559d4ea0c935
Reviewed-on: http://review.couchbase.org/70601
Reviewed-by: Pavel Paulau <pavel.paulau@gmail.com>
Tested-by: Pavel Paulau <pavel.paulau@gmail.com>