Skip bad latency measurements
Latency reservoir receives empty values when N1QL/Views queries
fail (e.g., due to timeout). We should skip these bad values so
that later aggregation doesn't break.

Fixes:

Traceback (most recent call last):
  File "env/bin/perfrunner", line 11, in <module>
    load_entry_point('perfrunner==0.0.0', 'console_scripts', 'perfrunner')()
  File "/home/workspace/triton/src/perfrunner/perfrunner/__main__.py", line 42, in main
    test.run()
  File "/home/workspace/triton/src/perfrunner/perfrunner/tests/n1ql.py", line 70, in run
    self.access()
  File "<decorator-gen-105>", line 2, in access
  File "/home/workspace/triton/src/perfrunner/perfrunner/helpers/cbmonitor.py", line 62, in with_stats
    test.cbagent.reconstruct()
  File "/home/workspace/triton/src/perfrunner/perfrunner/helpers/cbmonitor.py", line 319, in reconstruct
    collector.reconstruct()
  File "/home/workspace/triton/src/perfrunner/cbagent/collectors/reservoir.py", line 30, in reconstruct
    data = {self.METRICS[0]: float(latency) * 1000}  # Latency in ms
ValueError: could not convert string to float:

Change-Id: If059ed0ba177a722bb2f80e130e393b3fa4cb4e0
Reviewed-on: http://review.couchbase.org/74654
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Pavel Paulau <pavel.paulau@gmail.com>