Split complex N1QL titles
Some N1QL code names consist of multiple words. We need to handle
those cases as well. Otherwise we run into errors like this:

Change-Id: Ic09d6a31252c8d6c3f12bd3c782acda980a8f699
ValueError: invalid literal for int() with base 10: '3 Array Indexing'
Reviewed-on: http://review.couchbase.org/88871
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Alex Gyryk <oleksandr.gyryk@couchbase.com>